#pragma once

/**
* TPEGCommon.cginc
*/

#define BLOCK_AXIS_SIZE 8
#define BLOCK_AXIS_SIZE_LOG2 3

#define BLOCK_SIZE 64
#define BLOCK_SIZE_LOG2 6

#define YCrCb_SIZE 3
#define Y_IDX 0
#define Cr_IDX 1
#define Cb_IDX 2

#define DST_COLOR_SIZE 3
#define SRC_COLOR_SIZE 4

#define SHORT_TYPE_BIT_SIZE 16
#define SHORT_TYPE_BYTE_SIZE 2

#define INT_TYPE_BIT_SIZE 32
#define INT_TYPE_BYTE_SIZE 4

#define ENDIAN_BIT_SIZE 8
#define ENDIAN_SIZE 2

#define BLOCK_SIZE_RECV_AS_INT 32
#define BLOCK_SIZE_RECV_AS_INT_LOG2 5

#define PIXEL_MAX_VALUES 255
#define PIXEL_MAX_VALUES_LOG2 8
#define PIXEL_MAX_VALUES_INV 0.003921568627450f
